[package]
name = "do-math"
version = "0.1.0"
authors = ["Tom Steavenson <tomsteavenson@gmail.com>"]
edition = "2018"
publish = ["metaswitch"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.2"
num-integer = "0.1.41"
